### ISSUE TITLE
Failed to get driver instance

### ISSUE THREAD

**Issue by Jdewi12** [EnvyWare/ReforgedBingo#5]
Hi, I'm getting the following error with release 2.0.1 on a 1.16.5 Forge 36.2.35 server with Java 1.8.0_241:
<details>

```
[22Jun2022 01:24:08.755] [envyware_concurrency_0/INFO] [STDERR/]: [com.envyful.reforged.bingo.forge.shade.slf4j.impl.SimpleLogger:write:381]: [envyware_concurrency_0] INFO com.envyful.reforged.bingo.forge.shade.hikari.hikari.HikariDataSource - Bingo - Starting...
[22Jun2022 01:24:08.771] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/pixelmon_bingo
[22Jun2022 01:24:08.771] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
[22Jun2022 01:24:08.771] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:65)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:22)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.ReforgedBingo.lambda$onInit$0(ReforgedBingo.java:61)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[22Jun2022 01:24:08.772] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.sql.SQLException: No suitable driver
[22Jun2022 01:24:08.773] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.sql.DriverManager.getDriver(Unknown Source)
[22Jun2022 01:24:08.773] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.envyful.reforged.bingo.forge.shade.hikari.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
[22Jun2022 01:24:08.773] [envyware_concurrency_0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 10 more
```
</details>

I'm using MySQL Community Server 5.7.38. I'm pretty sure I've set up the database, user, permissions, etc. correctly, and have entered them correctly in the config file with the correct port. I've tried 127.0.0.1 as the ip too. I am able to manually log in via MySQL Workbench with the same details. There is nothing in the mysql error log.

I initially posted in the Pixelmon Reforged Discord server asking for help, and after a while another user said this:

> can tell, it's not an invalid connection, or less likely 
and can confirm that forge with spongeforge also didn't work by this case ^ 
> 
> just checked both 1.12.2 and 1.16.5, where in 1.12.2 the connection works without any doubt, while 1.16.5 gives me the error with the database aswell
so would assume that their update didn't really work out too well 😬 but yeah, there devs might be able to help better... 
and the localhost i used 127.0.0.1 to connect to

**Comment by danorris709** [comment]
This is an issue with your server. Google `Failed to get driver instance`

**Comment by snomnomnom** [comment]
> Hi, I'm getting the following error with release 2.0.1 on a 1.16.5 Forge 36.2.35 server with Java 1.8.0_241:
> 
> I'm using MySQL Community Server 5.7.38. I'm pretty sure I've set up the database, user, permissions, etc. correctly, and have entered them correctly in the config file with the correct port. I've tried 127.0.0.1 as the ip too. I am able to manually log in via MySQL Workbench with the same details. There is nothing in the mysql error log.
> 
> I initially posted in the Pixelmon Reforged Discord server asking for help, and after a while another user said this:
> 
> > can tell, it's not an invalid connection, or less likely
> > and can confirm that forge with spongeforge also didn't work by this case ^
> > just checked both 1.12.2 and 1.16.5, where in 1.12.2 the connection works without any doubt, while 1.16.5 gives me the error with the database aswell
> > so would assume that their update didn't really work out too well 😬 but yeah, there devs might be able to help better...
> > and the localhost i used 127.0.0.1 to connect to

Try installing this into your mods folder if you're running pure forge. 

https://www.curseforge.com/minecraft/mc-mods/mysql-jdbc/files/3685108

**Comment by Jdewi12** [comment]
> This is an issue with your server. Google Failed to get driver instance
I did google it, but didn't find anything relevant.

> Try installing this into your mods folder if you're running pure forge.
> 
> https://www.curseforge.com/minecraft/mc-mods/mysql-jdbc/files/3685108
This worked, thank you!

If this library is required, I'd suggest clarifying that in the error, noting it in the readme, or noting it on [the mod's pixelmonmod.com wiki page](https://pixelmonmod.com/wiki/Pixelmon_Bingo).
